"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-28 14:36:38.112406
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('security_domain', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('code', name=op.f('uq_role_code'))
    )
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('bootstrap_completed_at', sa.DateTime(), nullable=True),
    sa.Column('key_check', sa.String(length=64), nullable=True),
    sa.Column('next_entity_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace'))
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('username_normalized', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('security_domain', sa.String(length=20), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_app_user_created_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['app_user.id'], name=op.f('fk_app_user_updated_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_app_user_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('workspace_id', 'username_normalized', name='uq_user_ws_username')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=12), nullable=False),
    sa.Column('before_snapshot', sa.JSON(), nullable=True),
    sa.Column('after_snapshot', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=40), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], name=op.f('fk_audit_event_actor_user_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_audit_event_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_audit_object', ['object_type', 'object_id'], unique=False)

    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_auth_session_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_session_token_hash'))
    )
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_session_user_id'), ['user_id'], unique=False)

    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('entity_number', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=14), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=True),
    sa.Column('primary_contact', sa.String(length=200), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_financial_institution', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_entity_created_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['app_user.id'], name=op.f('fk_entity_updated_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_entity_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity')),
    sa.UniqueConstraint('workspace_id', 'entity_number', name='uq_entity_ws_number')
    )
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_is_financial_institution'), ['is_financial_institution'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_name_key'), ['name_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('fiscal_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=24), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('exception_confirmed', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['app_user.id'], name=op.f('fk_fiscal_year_approved_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['app_user.id'], name=op.f('fk_fiscal_year_closed_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_fiscal_year_created_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['app_user.id'], name=op.f('fk_fiscal_year_updated_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_fiscal_year_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_year')),
    sa.UniqueConstraint('workspace_id', 'identifier', name='uq_fy_ws_identifier')
    )
    with op.batch_alter_table('fiscal_year', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiscal_year_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_year_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_year_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_year_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_role_role_id_role')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_user_role_user_id_app_user')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_role'))
    )
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('financial_institution_entity_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('account_subtype', sa.String(length=60), nullable=True),
    sa.Column('account_number_ciphertext', sa.Text(), nullable=False),
    sa.Column('account_number_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('account_number_visible_suffix', sa.String(length=4), nullable=False),
    sa.Column('register_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('interest_rate', sa.String(length=12), nullable=True),
    sa.Column('opening_balance_cents', sa.BigInteger(), nullable=True),
    sa.Column('opening_balance_date', sa.Date(), nullable=True),
    sa.Column('manual_current_balance_cents', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('close_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_bank_account_created_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['financial_institution_entity_id'], ['entity.id'], name=op.f('fk_bank_account_financial_institution_entity_id_entity')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['app_user.id'], name=op.f('fk_bank_account_updated_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_bank_account_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_account')),
    sa.UniqueConstraint('workspace_id', 'account_number_fingerprint', name='uq_bank_ws_fingerprint')
    )
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_account_is_primary'), ['is_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_account_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_account_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('parent_budget_id', sa.Integer(), nullable=True),
    sa.Column('parent_code', sa.String(length=10), nullable=False),
    sa.Column('child_code', sa.String(length=6), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('budget_type', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('requested_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('system_managed', sa.Boolean(), nullable=False),
    sa.Column('is_other', sa.Boolean(), nullable=False),
    sa.Column('is_budget_zero', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_budget_created_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_year.id'], name=op.f('fk_budget_fiscal_year_id_fiscal_year')),
    sa.ForeignKeyConstraint(['parent_budget_id'], ['budget.id'], name=op.f('fk_budget_parent_budget_id_budget')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['app_user.id'], name=op.f('fk_budget_updated_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_budget_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget'))
    )
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_fiscal_year_id'), ['fiscal_year_id'], unique=False)
        batch_op.create_index('ix_budget_fy_type_status', ['fiscal_year_id', 'budget_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_parent_budget_id'), ['parent_budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('register_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('clear_date', sa.Date(), nullable=True),
    sa.Column('parent_entity_id', sa.Integer(), nullable=True),
    sa.Column('check_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('void_reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('voided_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('fk_register_transaction_bank_account_id_bank_account')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_register_transaction_created_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['entity.id'], name=op.f('fk_register_transaction_parent_entity_id_entity')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['app_user.id'], name=op.f('fk_register_transaction_updated_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['app_user.id'], name=op.f('fk_register_transaction_voided_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_register_transaction_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_register_transaction'))
    )
    with op.batch_alter_table('register_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_register_transaction_bank_account_id'), ['bank_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_transaction_clear_date'), ['clear_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_transaction_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_transaction_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_transaction_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('transaction_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], name=op.f('fk_transaction_allocation_budget_id_budget')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_transaction_allocation_created_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_transaction_allocation_entity_id_entity')),
    sa.ForeignKeyConstraint(['transaction_id'], ['register_transaction.id'], name=op.f('fk_transaction_allocation_transaction_id_register_transaction')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['app_user.id'], name=op.f('fk_transaction_allocation_updated_by_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_allocation'))
    )
    with op.batch_alter_table('transaction_allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_allocation_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_allocation_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=80), nullable=False),
    sa.Column('mime_type', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('removed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['transaction_allocation.id'], name=op.f('fk_attachment_allocation_id_transaction_allocation')),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_year.id'], name=op.f('fk_attachment_fiscal_year_id_fiscal_year')),
    sa.ForeignKeyConstraint(['removed_by_user_id'], ['app_user.id'], name=op.f('fk_attachment_removed_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['transaction_id'], ['register_transaction.id'], name=op.f('fk_attachment_transaction_id_register_transaction')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['app_user.id'], name=op.f('fk_attachment_uploaded_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_attachment_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_attachment_storage_key'))
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_allocation_id'), ['allocation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_fiscal_year_id'), ['fiscal_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('fiscal_year_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('transaction_allocation_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('natural_fiscal_year_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('review_note', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['natural_fiscal_year_id'], ['fiscal_year.id'], name=op.f('fk_fiscal_year_review_natural_fiscal_year_id_fiscal_year')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['app_user.id'], name=op.f('fk_fiscal_year_review_reviewed_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['transaction_allocation_id'], ['transaction_allocation.id'], name=op.f('fk_fiscal_year_review_transaction_allocation_id_transaction_allocation')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_fiscal_year_review_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_year_review'))
    )
    with op.batch_alter_table('fiscal_year_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiscal_year_review_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_year_review_transaction_allocation_id'), ['transaction_allocation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_year_review_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiscal_year_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiscal_year_review_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_fiscal_year_review_transaction_allocation_id'))
        batch_op.drop_index(batch_op.f('ix_fiscal_year_review_status'))

    op.drop_table('fiscal_year_review')
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_attachment_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_attachment_fiscal_year_id'))
        batch_op.drop_index(batch_op.f('ix_attachment_allocation_id'))

    op.drop_table('attachment')
    with op.batch_alter_table('transaction_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_allocation_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_allocation_budget_id'))

    op.drop_table('transaction_allocation')
    with op.batch_alter_table('register_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_register_transaction_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_register_transaction_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_register_transaction_status'))
        batch_op.drop_index(batch_op.f('ix_register_transaction_clear_date'))
        batch_op.drop_index(batch_op.f('ix_register_transaction_bank_account_id'))

    op.drop_table('register_transaction')
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_budget_parent_budget_id'))
        batch_op.drop_index('ix_budget_fy_type_status')
        batch_op.drop_index(batch_op.f('ix_budget_fiscal_year_id'))

    op.drop_table('budget')
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_account_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_bank_account_status'))
        batch_op.drop_index(batch_op.f('ix_bank_account_is_primary'))

    op.drop_table('bank_account')
    op.drop_table('user_role')
    with op.batch_alter_table('fiscal_year', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiscal_year_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_fiscal_year_status'))
        batch_op.drop_index(batch_op.f('ix_fiscal_year_start_date'))
        batch_op.drop_index(batch_op.f('ix_fiscal_year_end_date'))

    op.drop_table('fiscal_year')
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_entity_name_key'))
        batch_op.drop_index(batch_op.f('ix_entity_is_financial_institution'))
        batch_op.drop_index(batch_op.f('ix_entity_active'))

    op.drop_table('entity')
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_session_user_id'))

    op.drop_table('auth_session')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_object')
        batch_op.drop_index(batch_op.f('ix_audit_event_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_event_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_action'))

    op.drop_table('audit_event')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_workspace_id'))

    op.drop_table('app_user')
    op.drop_table('workspace')
    op.drop_table('role')
    # ### end Alembic commands ###
